// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB7a6CNy1C1yZBN4qwjeM5fqJLK_kZ3Lco',
    appId: '1:616624459091:web:2749d9f69b2453299165a6',
    messagingSenderId: '616624459091',
    projectId: 'apex-information-web',
    authDomain: 'apex-information-web.firebaseapp.com',
    storageBucket: 'apex-information-web.appspot.com',
    measurementId: 'G-Q3MJ6PLTKF',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDgbpCpRW1AtK6asbzNU9po7hFjsD87-50',
    appId: '1:616624459091:android:91f386de4c95840a9165a6',
    messagingSenderId: '616624459091',
    projectId: 'apex-information-web',
    storageBucket: 'apex-information-web.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDCF2dRZjoaG1KQgG1BIwpWF-BwCw1Ddpg',
    appId: '1:616624459091:ios:fda834ef0dc7d38b9165a6',
    messagingSenderId: '616624459091',
    projectId: 'apex-information-web',
    storageBucket: 'apex-information-web.appspot.com',
    iosClientId: '616624459091-j5528ais2i1sr76cqn9nqbkcdgkiiahn.apps.googleusercontent.com',
    iosBundleId: 'com.example.apexInfoWeb',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDCF2dRZjoaG1KQgG1BIwpWF-BwCw1Ddpg',
    appId: '1:616624459091:ios:fda834ef0dc7d38b9165a6',
    messagingSenderId: '616624459091',
    projectId: 'apex-information-web',
    storageBucket: 'apex-information-web.appspot.com',
    iosClientId: '616624459091-j5528ais2i1sr76cqn9nqbkcdgkiiahn.apps.googleusercontent.com',
    iosBundleId: 'com.example.apexInfoWeb',
  );
}
